spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.226.128:3306/gulimall_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
#        server-addr: 4418az5297.zicp.vip:8848
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag #全局逻辑删除的实体字段名
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 10000
